tetratelabs/func-e

.circleci/config.yml

Forgot to add this step... https://circleci.com/docs/2.0/building-docker-images/

turn on docker daemon in circleci

---

pkg/binary/envoy/debug/node.go
pkg/binary/envoy/debug/node_test.go

Signed-off-by: Taiki Ono <taiki@tetrate.io>
Fixes https://github.com/tetratelabs/getenvoy/issues/40
`Interfaces()` is just a wrapper of golang std's `Interfaces()` and it safely picks up interfaces. https://github.com/shirou/gopsutil/blob/v2.19.8/net/net.go#L212 And we can use JSON format to log interfaces at that time safely https://github.com/shirou/gopsutil/blob/v2.19.8/net/net.go#L193.
Output example:
```
[{"mtu":65536,"name":"lo","hardwareaddr":"","flags":["up","loopback"],"addrs":[{"addr":"127.0.0.1/8"},{"addr":"::1/128"}]},{"mtu":1500,"name":"eno1","hardwareaddr":"","flags":["up","broadcast","multicast"],"addrs":[{"addr":"192.168.11.7/24"},{"addr":""},{"addr":""},{"addr":""}]},{"mtu":1500,"name":"docker0","hardwareaddr":"","flags":["up","broadcast","multicast"],"addrs":[{"addr":"172 …
```

Implement network interfaces logging at exit

---

pkg/binary/envoy/debug/node.go
pkg/binary/envoy/debug/node_test.go

Previously, it writes invalid JSON string which lacks commas.
Signed-off-by: Taiki Ono <taiki@tetrate.io>
Follow-up of https://github.com/tetratelabs/getenvoy/pull/55.

Fix to output valid JSON string

---

pkg/binary/envoy/debug/node.go
pkg/binary/envoy/debug/node_test.go

On pre-termination.
Signed-off-by: Taiki Ono <taiki@tetrate.io>
https://github.com/tetratelabs/getenvoy/issues/38
Example:
```
[
{
"fd": 14,
"family": "AF_INET",
"type": "SOCK_STREAM",
"localaddr": {
"ip": "192.168.11.11",
"port": 57219
},
"remoteaddr": {
"ip": "192.168.11.9",
"port": 55563
},
"status": "ESTABLISHED",
"uids": null,
"pid": 297
}
]
```

Log all connections on the machine

---

pkg/binary/envoy/termination.go

```
go run cmd/getenvoy/main.go run standard:1.11.0 -- --version
2019-10-27T09:48:59.808199Z	error	Log collection is not supported on this Operating System
2019-10-27T09:48:59.808381Z	warn	Running on a non-Linux system, cannot set child process kill signal. Some cases where this process terminates before the Envoy child process may not be handled gracefully.
2019-10-27T09:48:59.808473Z	info	Envoy command: [/Users/liam/.getenvoy/builds/standard/1.11.0/darwin/bin/envoy --version]
/Users/liam/.getenvoy/builds/standard/1.11.0/darwin/bin/envoy  version: bf169f9d3c8f4c682650c5390c088a4898940913/1.11.0/clean-getenvoy-af8a2e7/RELEASE/BoringSSL
2019-10-27T09:48:59.876601Z	info	No Envoy processes remaining, terminating GetEnvoy process (PID=44414)
2019-10-27T09:48:59.876634Z	info	Envoy process …
```

handle successful envoy return codes

---

.goreleaser.yaml

See https://goreleaser.com/deprecations/#docker-binary

remove deprecated field

---

.goreleaser.yaml
pkg/binary/envoy/fetch.go
pkg/cmd/root.go
pkg/manifest/print.go
pkg/transport/client.go
pkg/transport/client_test.go
pkg/version/version.go

This patch will add user-agent on requesting external endpoint such as fetching envoy binary or manifest. This enables us to know which version users use and make it easier to support GetEnvoy users.
The format of user-agent is `GetEnvoy/{Version}`.
Signed-off-by: Kotaro Inoue k.musaino@gmail.com

Add user-agent on requesting external url

---

go.mod
go.sum
pkg/binary/envoy/config.go
pkg/binary/envoy/runtime.go
pkg/binary/interface.go
pkg/cmd/run.go
pkg/flavors/flavors.go
pkg/flavors/flavors_test.go
pkg/flavors/postgres/postgres.go
pkg/flavors/postgres/postgres_test.go

Added logic to recognize _postgres_ flavor and bootstrap config based on template and command line parameters.
Command line parameters are specified by --templateArg. More than one templateArg may be specified. For Postgres a user must specify Endpoint, like --templateArg Endpoint=127.0.0.1
Additional parameter is InPort, which is Envoy's listening port. If not specified the value of InPort defaults to 5432.
To overwrite InPort, cmd line should contain --templateArg InPort=5433

Add postgres experience

---

.github/workflows/builders.yml
Makefile

* fix CI build that fails on attempt to `docker push` the `latest` builder image, while `latest` tag has never been added

ci: fix `make builders.push BUILDERS_TAG=latest`

---

.github/workflows/release.yaml

Looks like the current release flow pushes builder images with `vx.y.z` which is prefixed by "v'" since `BUILDERS_TAG` is set to be the release tag.
https://github.com/tetratelabs/getenvoy/runs/2110465245?check_suite_focus=true
```
Run make builders.push BUILDERS_TAG=v0.2.1
docker push getenvoy/extension-rust-builder:v0.2.1
....
docker push getenvoy/extension-tinygo-builder:v0.2.1
....
```
And this results in `getenvoy extension {test,build}` failures with image not found:
```
getenvoy extension build
Unable to find image 'getenvoy/extension-rust-builder:0.2.1' locally
docker: Error response from daemon: manifest for getenvoy/extension-rust-builder:0.2.1 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Error: failed to build Envoy extension using "default" …
```

Fix builders tags

---

.github/workflows/release.yaml

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
Fix the failure in e2e in release pipeline: https://github.com/tetratelabs/getenvoy/runs/2110493412?check_suite_focus=true
```
Run curl -s https://raw.githubusercontent.com/dsaltares/fetch-gh-release-asset/0.0.5/fetch_github_asset.sh | bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9953  100  9953    0     0  99530      0 --:--:-- --:--:-- --:--:-- 99530
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   120  100   120    0 …
```

Fix e2e on release

---

.github/workflows/builders.yml
.github/workflows/commit.yaml
.github/workflows/release.yaml
Makefile
ci/e2e/macos/.licenserignore
ci/e2e/macos/install_docker.sh
pkg/binary/envoy/debug/node_test.go

The former script to install docker fails and also has dead links
describing why it was written. This replaces the script with one updated
this month, and with history and license info about where it came from.

Formats CI yaml and switches to a recent install_docker script

---

.golangci.yml
Makefile
pkg/binary/envoytest/util.go
pkg/extension/init/init.go
pkg/extension/workspace/toolchain/builtin/toolchain.go

Fixes lint setup to skip embedded tinygo examples

---

.github/workflows/commit.yaml
ci/e2e/macos/install_docker.sh

Signed-off-by: Yaroslav Skopets <yaroslav@tetrate.io>
* this PR sets deadlines for `e2e` test jobs on `Mac` to avoid wasting resources for `6 hours` when `Docker for Mac` fails to install correctly
* This PR is based on `master` prior to #135 
* This PR only makes sense if #135  is reverted from `master`
* If this PR is merged on `master` without reverting #135, it will cause all builds to fail (because they take `3,5+ hours` and this PR is trying to prevent that)

ci: add timeouts to GHA jobs and steps to avoid e2e tests holding MacOS environment for 6 hours

---

.github/workflows/commit.yaml
.github/workflows/release.yaml
ci/e2e/macos/.licenserignore
ci/e2e/macos/install_docker.sh

The old script that was failing to install and swapped out in #135 works again. This reverts it until we can diagnose what's behind the hanging in #145, or something else fixes it.
Fixes #140

Reverts to old macos install_docker.sh

---

pkg/cmd/extension/push/cmd.go

Recent docker tools require fully resolved image tags (ex :latest
explicitly). While we ensured the latest tag was appended, we didn't use
it. I noticed this pushing to my local registry on latest OS/x and Docker.

Fixes bug where fully resolved image ref wasn't used

---

ci/e2e/macos/install_docker.sh

The one we used before relies on docker.io which is rate-limited.
See #149

Uses alternative source for busybox image in osx script

---

pkg/binary/envoy/debug/admin_test.go
pkg/binary/envoy/debug/lsof_test.go
pkg/binary/envoy/fetch.go
pkg/manifest/locate.go
pkg/manifest/locate_test.go
pkg/manifest/print.go
pkg/types/reference.go

Before, we mixed format of `Reference.Platform` to sometimes enum and
other times lower-hyphen format. This is confusing and leads to subtle
bugs. For example, some code did simply a lowercase and forgot to
convert underscores to hyphens.
This change normalizes to always write lower-hypen.
This also fixes a couple tests which panic'ed due to #137, but were
otherwise unrelated.

Normalizes Reference.Platform to lower-hyphen format

---

images/extension-builders/entrypoint.sh
images/extension-builders/rust/Dockerfile
images/extension-builders/rust/commands.sh
images/extension-builders/tinygo/commands.sh
pkg/cmd/extension/build/cmd_test.go
pkg/cmd/extension/clean/cmd_test.go
pkg/cmd/extension/run/cmd_test.go
pkg/cmd/extension/test/cmd_test.go
pkg/extension/workspace/toolchain/builtin/toolchain.go
pkg/extension/workspace/toolchain/builtin/toolchain_test.go

The current way we build extensions is to mount a volume containing a directory created by "getenvoy extension init" in a "docker run" command. This implies a "bind mount" which is slow on macOS and particularly slow in rust (cargo) builds. This topic has locked our project into an old docker script, and even then it is quite slow.
This change tries to work around the problem by sharing information about the docker host (eg the machine calling `getenvoy`). What it does is propagates runtime.GOOS as docker env GETENVOY_GOOS. The rust builder image looks at this and optimizes if it is macOS.
While there are other optimizations we should address in #152, this should make enough difference to allow us to upgrade docker.

Propagates runtime.GOOS as docker env GETENVOY_GOOS to speed up rust

---

images/extension-builders/tinygo/commands.sh

Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
Previously, when `go {test,build}` fails, chmod would never be called. That would cause the nasty permission denied error when test/build failures occur during e2e as well as users try to remove an extension dir after failure.

Execute chmod for TinyGo gocache on trap

---

.github/workflows/commit.yaml
.github/workflows/internal-images.yml
Makefile
ci/e2e/darwin/install_docker.sh
docker-compose.yml
images/extension-builders/rust/Dockerfile
images/extension-builders/tinygo/Dockerfile
pkg/cmd/extension/push/cmd_test.go

Each pull request implies many docker.io requests, this has led to
builds failing on account of rate limiting. This avoids that by using
the GitHub Container Registry (ghcr.io) instead of Docker Hub
(docker.io). ghcr.io is not rate-limited. Specifically, we use internal
copies of images used as parents or in testing. Since these aren't what
end users use anyway, this doesn't impact them.
At the end of the day, ghcr.io/tetratelabs/getenvoy-internal has tags
corresponding to our needs:
```yaml
- source: busybox:1.32.1  # test image: ci/e2e/darwin/install_docker.sh
target_tag: busybox
- source: registry:2  # test image: docker-compose.yml
target_tag: registry
- source: rust:1.51.0  # parent image: images/extension-builders/rust/Dockerfile
target_tag: rust
- source: tinygo/tinygo:0.17.0  # …
```

Fixes docker.io normal case rate-limiting

---

pkg/binary/envoy/controlplane/istio_test.go
pkg/binary/envoy/debug/admin_test.go
pkg/binary/envoy/debug/log.go
pkg/binary/envoy/debug/log_test.go
pkg/binary/envoy/debug/lsof_test.go
pkg/binary/envoy/debug/node_test.go
pkg/binary/envoy/run.go
pkg/binary/envoy/run_test.go
pkg/binary/envoy/runtime.go
pkg/binary/envoy/termination.go
pkg/binary/envoytest/util.go
pkg/binary/interface.go

Before, we had complex signal handling in both "getenvoy run" and also
normal command invocation. This solves the first part by reducing the
amount of gears used to run the process, and also moving to
NotifyContext for signal interception.
See #172 for more information on NotifyContext, though this change
doesn't remove the osutil functions, yet. That will be a different PR
as it is a different branch of code.

Cleans signal handling and reduces complexity of "getenvoy run"

---

data/extension/init/templates/rust/envoy.access_loggers/default/Cargo.toml
data/extension/init/templates/rust/envoy.access_loggers/default/src/config.rs
data/extension/init/templates/rust/envoy.filters.http/default/Cargo.toml
data/extension/init/templates/rust/envoy.filters.http/default/src/config.rs
data/extension/init/templates/rust/envoy.filters.network/default/Cargo.toml
data/extension/init/templates/rust/envoy.filters.network/default/src/config.rs

Before, we had a significantly larger dependency tree than needed for
deserializing json:
```
envoy-sample-access-logger-module v0.1.0 (/Users/adrian/tetratelabs/getenvoy/data/extension/init/templates/rust/envoy.access_loggers/default/wasm/module)
├── envoy-sample-access-logger v0.1.0 (/Users/adrian/tetratelabs/getenvoy/data/extension/init/templates/rust/envoy.access_loggers/default)
│   ├── envoy-sdk v0.2.0-alpha.1
│   │   ├── anyhow v1.0.40
│   │   ├── bitflags v1.2.1
│   │   ├── log v0.4.14
│   │   │   └── cfg-if v1.0.0
│   │   └── proxy-wasm-experimental v0.0.8
│   │       ├── hashbrown v0.9.1
│   │       │   └── ahash v0.4.7
│   │       └── log v0.4.14 (*)
│   ├── serde v1.0.125
│   │   └── serde_derive v1.0.125 (proc-macro)
│   │       ├── proc-macro2 v1.0.26
│   │       │   └── …
```

Makes rust examples use a smaller dependency for json

---

.goreleaser.yaml

Our goreleaser file differs from our Makefile in so far as including 386
arch. We should focus on what users are asking for instead.
This also removes the implicit go modules default as we set go to 1.16.

Removes 386 release as no-one asked for it

---

go.mod
go.sum
pkg/cmd/root.go
pkg/cmd/root_test.go
pkg/globals/globals.go

Recent refactoring deferred lookup of the user home dir until after
GETENVOY_HOME is checked. This prefers being strict vs using an
undefined value on error determining the user home.

Prefers quitting vs using an incoherent homedir

---

go.mod
go.sum
pkg/binary/envoy/fetch_test.go
pkg/test/manifest/server.go

Uses normal regex instead of lib dep in unit tests

---

go.mod
go.sum
internal/tar/tar.go
internal/tar/tar_test.go
pkg/binary/envoy/fetch.go
pkg/binary/envoy/fetch_test.go
pkg/binary/envoy/termination.go
pkg/test/manifest/manifest.go
pkg/test/manifest/server.go
test/e2e/getenvoy_run_test.go

This removes the dependency on "archiver/v3" from the binary because
* It has no support for streaming https://github.com/mholt/archiver/pull/199, so we had to buffer to disk first
* Including "archiver/v3" makes it easy to accidentally bloat the binary (we did this by 25% before)
* The result is simpler dependencies
Before:
```bash
$ du -sk build/bin/*/*/getenvoy
8020	build/bin/darwin/amd64
7528	build/bin/linux/amd64
```
```bash
$ du -sk build/bin/*/*/getenvoy
7728	build/bin/darwin/amd64
7264	build/bin/linux/amd64
```

Drops compile dep on archiver/v3

---

.github/workflows/commit.yaml
.gitignore
Makefile
README.md

This removes so many variable no one would set, fixes coverage packages and makes sure it builds into the ./coverage directory. Coverage is now analyzed with codecov.io
Fixes #186

Simplifies coverage configuration and replaces manual analysis with codecov.io

---

e2e/getenvoy_test.go
internal/cmd/versions.go
internal/cmd/versions_test.go
internal/envoy/versions.go
internal/envoy/versions_test.go
internal/test/server.go

Ex.
```bash
$ dist/getenvoy_darwin_amd64/getenvoy versions
VERSION	RELEASE_DATE
1.18.3	2021-05-11
1.17.3	2021-05-11
1.16.4	2021-05-11
1.15.5	2021-05-11
1.14.7	2021-04-15
```
fixes #93

Adds release date to version list output

---

.github/workflows/commit.yaml
e2e/command_test.go
e2e/getenvoy_install_test.go
e2e/getenvoy_installed_test.go
internal/cmd/app.go
internal/cmd/help_test.go
internal/cmd/installed.go
internal/cmd/installed_test.go
internal/cmd/testdata/getenvoy.md
internal/cmd/testdata/getenvoy_help.txt
internal/cmd/testdata/getenvoy_installed_help.txt

Before, we only had a command to know the available versions. This tells
us what's installed. Later, we can print out which is the default
version.
Rationale for "installed" is that it is intuitive alongside "install" vs other options. Also, the fact that "getenvoy" is not an env-based name makes it look nicer (IMHO)
Ex.
```bash
getenvoy versions (existing command)
getenvoy install 1.18.3 (existing command)
getenvoy installed (new command)
```
Vs. Mixing different output based on a flag like `pyenv install`
```bash
pyenv install -l
pyenv install  3.9.5
pyenv versions
```
Vs. not really describing versions are the thing 'ls'ed like `nvm`
```bash
nvm ls-remote
nvm install v16.2.0
nvm ls
```

Adds `getenvoy installed` to list installed versions

---

.licenserignore
.travis.yaml

This adds travis configuration which we can validate for amd64. Once we have an envoy binary, all we need to do is switch the arch to "amd64" or "arm64-graviton2" I think we can use the latter since we don't require our tests to run docker. It is supposedly very fast. https://blog.travis-ci.com/2020-09-11-arm-on-aws
See #82

Enable travis in preparation of arm64 builds

---

e2e/getenvoy_run_test.go
internal/cmd/app.go
internal/cmd/app_test.go
internal/cmd/help_test.go
internal/cmd/install.go
internal/cmd/install_test.go
internal/cmd/run.go
internal/cmd/run_test.go
internal/cmd/testdata/getenvoy.md
internal/cmd/testdata/getenvoy_help.txt
internal/cmd/testdata/getenvoy_install_help.txt
internal/cmd/testdata/getenvoy_installed_help.txt
internal/cmd/testdata/getenvoy_run_help.txt
internal/cmd/testdata/getenvoy_versions_help.txt
internal/envoy/version.go
internal/envoy/version_test.go
internal/globals/globals.go
internal/test/morerequire/morerequire.go
main.go
main_test.go

This removes the version argument so that you can `getenvoy run`
without knowing which version you want first.
Ex.
```bash
$ getenvoy run --config-yaml "admin: {access_log_path: '/dev/stdout', address: {socket_address: {address: '127.0.0.1', port_value: 0}}}"
looking up latest version
downloading https://dl.getenvoy.io/public/raw/files/getenvoy-envoy-1.18.3.p0.g98c1c9e-1p77.gb76c773-darwin-release-x86_64.tar.xz
--snip--
```
The version of Envoy run is chosen from $ENVOY_VERSION (value),
$PWD/.envoy-version (file contents), $GETENVOY_HOME/version (file
contents).
The ENV allows people who really want to control the version to do so,
and without effecting the arg parsing of `envoy`.
When first run $GETENVOY_HOME/version is initialized the the remote
version stored as "lastestVersion" in the …

Removes need to specify an envoy version when running

---

e2e/command_test.go
e2e/main_test.go
internal/cmd/app.go
internal/cmd/app_test.go
internal/cmd/run.go
internal/cmd/versions.go
internal/envoy/http.go
internal/envoy/http_test.go
internal/envoy/install.go
internal/envoy/install_test.go
internal/envoy/versions.go
internal/globals/globals.go
internal/test/server.go

This also captures that netlify won't help us know which user-agents are in use without custom edge handlers.

Buckets user-agent only to release or non-release without an internal flag

---

.github/untar-getenvoy-release.sh
.github/workflows/release.yaml
.gitignore

The script we were using doesn't handle draft releases. This rewrites
the script so that we can test our binaries before announcing them via a
published release.

Fixes release test

---

Makefile

the last release e2e started implicitly kicking off the build due to a make glitch

Stops building the binary on-demand during release e2e

---

.licenserignore
e2e/admin_test.go
e2e/command_test.go
e2e/getenvoy_run_test.go
e2e/static-filesystem.yaml
internal/cmd/run.go
internal/cmd/run_test.go
internal/cmd/testdata/getenvoy_run_help.txt
internal/envoy/debug/admin.go
internal/envoy/debug/admin_test.go
internal/envoy/debug/log.go
internal/envoy/debug/lsof.go
internal/envoy/debug/node.go
internal/envoy/run.go
internal/envoy/run_test.go
internal/envoy/runtime.go
internal/envoy/start.go
internal/envoy/start_test.go
internal/envoy/termination.go
internal/globals/globals.go
internal/test/server.go

This makes sure Envoy is run in the current working directory, so that
it is easier to use and configuration can locate relative paths.
Fixes #263

Runs Envoy in the current working directory

---

.github/workflows/commit.yaml
e2e/admin_test.go
e2e/getenvoy_run_test.go
e2e/getenvoy_use_test.go
e2e/main_test.go
internal/cmd/run.go
internal/cmd/testdata/getenvoy_run_help.txt
internal/envoy/run.go
internal/envoy/run_test.go
internal/envoy/runtime.go
internal/envoy/runtime_test.go
internal/envoy/shutdown.go
internal/moreos/moreos.go
internal/moreos/proc.go
internal/moreos/proc_linux.go

This creates a foundation for future work by ensure Envoy is killed as
expected. Before, we weren't checking at all or weren't checking
propertly depending on the test.
This also does more hardening around timeouts by sharing a single parent
context during e2e run tests.

Writes envoy.pid and verifies Envoy is killed in e2e tests

---

.travis.yml

By using travis instead of a self-hosted github action, we don't pay anything to test arm64 and neither do non-employees who fork our repository.
This uses a temporary version list until our main one includes arm64
#109

Enables e2e testing of arm64 builds

---

internal/globals/globals.go
internal/test/server.go

Permits using a debug version
Debug versions are massive (2GB) and not available for all platforms. However, if someone has a supported platform, they should be able to use them.
Ex. on ubuntu:20.04
```bash
$ export ENVOY_VERSIONS_URL=https://archive.tetratelabs.io/envoy/envoy-versions_debug.json
$ getenvoy run --version
looking up latest version
downloading https://archive.tetratelabs.io/envoy/download/v1.18.3_debug/envoy-v1.18.3_debug-linux-amd64.tar.xz
starting: /root/.getenvoy/versions/1.18.3_debug/bin/envoy --version --admin-address-path /root/.getenvoy/runs/1624003987461190188/admin-address.txt
/root/.getenvoy/versions/1.18.3_debug/bin/envoy  version: 98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/Clean/RELEASE/BoringSSL
$ find /root/.getenvoy/versions/1.18.3_debug/ …
```

Permits using a debug version

---

README.md
site/content/index.md

we serve install.sh directly from the CDN, so there's no need to add complicated flags

Removes unnecessary redirect

---

.github/workflows/commit.yaml
.travis.yml

This prevents CI-only changes from tripping each other. It also skips more doc related stuff. Doing so will help conserve our free arm64 credits for real change.
AFAICT netlify will skip when it should anyway https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds

Fixes skip config

---

.travis.yml

This does two things to conserve arm64 time.
* run `make check` *after* checking if the build should run!
* cache the same directories we do in GH actions

Optimizes Travis check

---

.goreleaser.yaml
internal/cmd/app.go
internal/cmd/help_test.go
internal/cmd/run.go
internal/cmd/testdata/func-e_help.txt
internal/cmd/testdata/func-e_use_help.txt
internal/cmd/use.go
internal/cmd/versions.go
internal/envoy/http_test.go
internal/envoy/install_test.go
internal/globals/globals.go
internal/version/version.go
main.go

This makes the main version more normal. Ex.
```bash
$ go build -ldflags "-s -w -X main.version=foo" .
$ ./func-e -v
func-e version foo
```
This also gets rid of some shell games in static text tests.

Simplifies version override so it is more like other packages

---

USAGE.md
internal/cmd/app.go
internal/cmd/app_test.go
internal/cmd/run.go
internal/cmd/testdata/func-e_help.txt
internal/cmd/use.go
internal/cmd/versions.go
internal/envoy/http_test.go
internal/envoy/install.go
internal/envoy/install_test.go
internal/globals/globals.go

This PR adds a CLI flag for specifying a target platform for the Envoy install. This also includes the ability to specify a target platform through an environment variable.
Closes #299

Adds FUNC_E_PLATFORM to override host OS and architecture used to run Envoy

---

internal/envoy/install.go
internal/envoy/install_test.go
internal/tar/tar.go
internal/tar/tar_test.go

It is currently difficult to tell if tar is related to the SHA-256
mismatch on windows, but not Linux. Better tests make it easier to
figure out and fix.

Refactors SHA-256 code to isolate problem on Windows

---

internal/cmd/run.go
internal/envoy/runtime.go
internal/envoy/shutdown.go

This moves the logic that closes the stdout and stderr log to a place
where it can be closed explicitly before archive. Before, some paths
wouldn't close them, for example `func-e run --version` or anything else that didn't result in a listening process.

Makes stdout.log and stderr.log close explicit

---

.gitignore
internal/cmd/app.go
internal/cmd/help_test.go
internal/cmd/run.go
internal/cmd/run_test.go
internal/cmd/use.go
internal/cmd/versions.go
internal/cmd/versions_cmd_test.go
internal/envoy/install.go
internal/envoy/install_test.go
internal/envoy/run.go
internal/envoy/run_test.go
internal/envoy/shutdown.go
internal/envoy/shutdown/node.go
internal/moreos/moreos.go
internal/moreos/moreos_test.go
internal/moreos/proc_darwin.go
internal/moreos/proc_linux.go
internal/test/envoy.go
internal/test/server.go
main.go
main_test.go

This replaces `moreos.LineSeparator` with `moreos.Sprintf` and `Fprintf` in order to address all places where newlines need to change.
See https://github.com/golang/go/issues/28822

Completes Windows EOL handling

---

.github/workflows/release.yaml
Makefile
e2e/README.md
e2e/main_test.go

This refactors E2E tests to not rely on make. This gives us more flexibility in windows and also for how we download the release binary.

Refactors e2e to not rely on make

---

.github/workflows/commit.yaml
.github/workflows/release.yaml

https://github.com/golang/go/issues?q=milestone%3AGo1.16.6+label%3ACherryPickApproved

Builds with Go 1.16.6

---

internal/envoy/run.go
internal/moreos/moreos.go
internal/moreos/moreos_test.go
internal/moreos/proc_darwin.go
internal/moreos/proc_linux.go

We currently don't ensure Envoy has exited when it said it should. Due the the nature of FS locks in windows, we can detect this happens sometimes in #309. This change adds the plumbing we can use on all supported operating systems.

Adds hook to ensure Envoy exited

---

.goreleaser.yaml

zip is more idiomatic on that platform. I tested locally by pretending this commit was a release tag.
```bash
$ git tag -d v0.6.0
$ git tag v0.6.0
$ goreleaser-v0.173.2 release --skip-publish  --rm-dist
$ jar -tvf dist/func-e_0.6.0_windows_amd64.zip
11337 Tue Jul 06 00:14:16 ChST 2021 LICENSE
1177 Sat Jul 10 09:43:35 ChST 2021 README.md
7550976 Tue Jul 27 13:54:31 ChST 2021 func-e.exe
```

Makes windows use zip instead of tar.gz

---

.github/workflows/release.yaml

Last release, I manually did this:
```bash
$ brew bump-formula-pr func-e --version 0.6.0
```
This does the same, using the exact token which I added as a repo
secret.
fixes #317

Automates updating official homebrew formula

---

.github/workflows/commit.yaml
.licenserignore
Makefile
e2e/main_test.go
internal/moreos/proc_windows.go

This consolidates the build by using the same matrix for Linux, MacOS
and Windows. To do the latter requires installation of CygWin, and to
get GHA to use that requires overriding the `shell`. One other quirk is
that when you are running tasks via cygwin, it resets the CWD. To avoid
that, this adds the GITHUB_WORKSPACE to `.bashrc`. Finally, this dodges
various newline related problems and comments why.
Unrelated changes including updating syntax that allows us to
break-apart actions/cache and fixing some lint errors that the build
never caught because lint wasn't run on Windows.

Uses make in windows

---

.bingo/README.md
.bingo/Variables.mk
.github/workflows/commit.yaml

This restricts the default make config to single-entry GOPATH, which allows windows to work without hacks or cygwin.
Those who must use multiple-entry GOPATH will have to override GOBIN if they use our Makefile
See https://github.com/bwplotka/bingo/issues/26
This defers porting to go 1.17 #314

Restricts default make config to single-entry GOPATH

---

.github/workflows/release.yaml
Makefile

This adds func-e.msi manually until https://github.com/goreleaser/goreleaser/issues/1295
This also adds basic testing of the msi as a part of e2e.

Adds Windows Installer (MSI) to the release

---

.github/workflows/bump.yaml
.github/workflows/commit.yaml
.github/workflows/msi.yaml
.github/workflows/release.yaml

This uses a separate workflow for version bumps, starting with homebrew (winget is likely next).
This allows us to centralize flows that are not file-driven, rather release driven. Particularly, actions that result in external pull requests would end up here.
This converts the homebrew bump to explicit commands and also removes the need to say "same perms as `brew bump-formula-pr func-e --version 0.6.0`" as we literally are using that command.
This also centralizes the token and identity of those pull requests so they are attributed to the org, not the person who created the token.

Uses separate workflow for version bumps

---

USAGE.md
e2e/func-e_which_test.go
internal/cmd/app.go
internal/cmd/help_test.go
internal/cmd/run.go
internal/cmd/run_test.go
internal/cmd/testdata/func-e_help.txt
internal/cmd/testdata/func-e_which_help.txt
internal/cmd/which.go
internal/cmd/which_test.go
internal/envoy/install.go
internal/globals/globals.go

This adds a `which` command that prints the path to the Envoy binary
that would be run.
Ex.
```bash
$ func-e which
/Users/adrian/.func-e/versions/1.19.0/bin/envoy
```
This allows func-e to install, but not run envoy for scenarios such as building other images.
Ex. the following are equivalent:
```bash
$ $(func-e which) --version
$ func-e run --version
```

Adds which command

---

.github/workflows/commit.yaml
.github/workflows/internal-images.yml
.travis.yml

centos isn't a supported runner in GHA or travis, but you can run it via container with GHA.
We need to use an internal image to avoid rate limiting and 12minutes to install prereqs
See #338

Runs e2e on centos 8

---

packaging/msi/verify_msi.cmd

hopefully, this will prevent a flake like this https://github.com/tetratelabs/func-e/runs/3318938205
I used 2 seconds because that's the last magic number choco uses https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/AutomaticUninstallerService.cs#L41

sleep to prevent flakes  on delayed windows installer service

---

.github/workflows/release.yaml
packaging/msi/verify_msi.cmd

This reverts #341 as the root problem was a leftover file.

Ensures release testing of Windows installer works

---

.github/workflows/bump.yaml

This reverts to the old homebrew script because handing homebrew updates
in github env is a little tricky. This also adds a missing dep.
See https://github.com/tetratelabs/func-e/runs/3319457023?check_suite_focus=true

Fixes glitches in package update script

---

e2e/func-e_run_test.go
e2e/func-e_use_test.go
e2e/func-e_versions_test.go
internal/cmd/app_test.go
internal/cmd/run_test.go
internal/cmd/versions_cmd_test.go
internal/cmd/versions_test.go
internal/envoy/install_test.go
internal/envoy/run_test.go
internal/envoy/runtime.go
internal/envoy/runtime_test.go
internal/envoy/shutdown/admin_test.go
internal/envoy/shutdown/node_test.go
internal/envoy/version_test.go
internal/moreos/moreos_test.go
internal/tar/tar_test.go
internal/test/envoy.go
internal/test/morerequire/morerequire.go
internal/test/server.go
internal/test/testdata/fake_envoy.go

Some tests passed for the wrong reason because of drift in CLI parsing
inside the fake envoy server. This fixes that and also moves the fake
admin endpoint into the fake envoy server. This allows us to verify
admin address path parsing works as we expect it to.

Cleans up tests

---

internal/cmd/app_test.go
internal/cmd/versions_cmd_test.go
internal/envoy/version_test.go
internal/test/morerequire/morerequire.go

Notably, this uses the go 1.17 https://pkg.go.dev/testing#T.Setenv

Removes test utilities for built-ins

---

internal/cmd/run_test.go
internal/envoy/runtime.go
internal/envoy/runtime_test.go

As the flake isn't OS-specific (failed on linux, too), I changed the code to be more lenient. I also removed most of the code around Runtime.String() as it didn't help in debugging.

Pares down code to work around flake

---

Next.mk

Doing this as a separate file helps #352 not become massive.
Ex.

Scaffold a new Makefile

---

.github/workflows/msi.yaml
.gitignore
Next.mk
packaging/msi/verify_msi.cmd
packaging/msi/winget_manifest.sh

This removes the dependency on goreleaser by implementing what it does
in make.
This will fix #352 once the release process uses it, which will be a
different PR.
```bash
± |make-dist {3} ✓| → file dist/*
dist/func-e_dev_checksums.txt:       ASCII text
dist/func-e_dev_darwin_amd64.tar.gz: gzip compressed data, last modified: Sun Aug 29 04:19:00 2021, from Unix, original size modulo 2^32 7503360
dist/func-e_dev_darwin_arm64.tar.gz: gzip compressed data, last modified: Sun Aug 29 04:19:01 2021, from Unix, original size modulo 2^32 7743488
dist/func-e_dev_linux_amd64.tar.gz:  gzip compressed data, last modified: Sun Aug 29 04:19:01 2021, from Unix, original size modulo 2^32 7005696
dist/func-e_dev_linux_arm64.tar.gz:  gzip compressed data, last modified: Sun Aug 29 04:19:02 2021, from Unix, …
```

Generates release assets without goreleaser on 'make dist'

---

.github/workflows/release_notes.sh
.mailmap

This will be used in the new release process to generate draft release
notes that a person edits before clicking publish.
Notably, this correctly annotates co-authors, which is a common practice
in func-e, but easy to miss.
Ex. (nevermind the 'aster' as I'm hacking this to show pending notes)
```bash
$ .github/workflows/release_notes.sh master
```
---
---
func-e aster supports X and Y and notably fixes Z
TODO: classify the below into up to 4 major headings and the rest as bulleted items in minor changes
The published release notes should only include the summary statement in this section.
ee700a1 Converts e2e to new Makefile (#356) Adrian Cole, Co-authored-by: Dhi Aurrahman <dio@rockybars.com>
83e7c30 updates last known Envoy to 1.19.1 (#355) Adrian Cole, 
f975609 Aligns make to func-e …

Adds release notes generation script

---

Makefile

This adds sources (`*.go` except `*_test.go`) as prerequisites for building
the `current_binary` target. This forces rebuilding the `current_binary` 
target when any of `*.go` is changed.
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

build: Add *.go as prerequisite for building current binary

---

e2e/README.md

This updates the e2e README file with more clues and clarifies `dist` vs.
`build` directory.
Co-authored-by: Adrian Cole <adrian@tetrate.io>
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

Add more clues when running e2e test

---

internal/cmd/app.go
internal/cmd/app_test.go
internal/cmd/run.go
internal/cmd/versions.go
internal/envoy/install.go
internal/envoy/install_test.go
internal/envoy/versions.go
internal/envoy/versions_test.go
internal/globals/globals.go
internal/version/versions.go

This patch introduces FuncEVersions as an interface for easier testing,
especially when simulating failure on getting the remote Envoy release
versions map.
This also provides the default implementation of FuncEVersions, which
converts the existing functionality via Get() method and also a way to
find a latest patch given Envoy release versions map and a minor
version.
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

Add FuncEVersions interface and its default implementation

---

USAGE.md
e2e/func-e_use_test.go
internal/cmd/app.go
internal/cmd/run.go
internal/cmd/testdata/func-e_help.txt
internal/cmd/testdata/func-e_use_help.txt
internal/cmd/use.go
internal/cmd/use_test.go
internal/envoy/version.go
internal/globals/globals.go
internal/globals/globals_test.go
internal/version/version.go

This changeset introduces a way to switch the Envoy version using compatible
Envoy version (for example 1.18) and automatically infer the available
patched version to be downloaded. For instance, if the currently
downloaded version is 1.18.3, and the remote one has 1.18.4, calling
"use" downloads and sets the current version to 1.18.4.
Fixes #360 
Signed-off-by: Dhi Aurrahman <dio@tetrate.io>

Allow to "use" minor versions

---

.github/workflows/commit.yaml
internal/test/morerequire/morerequire.go

This fixes the timezone bug when doing `Chtimes`. By default `time.Parse`
uses `UTC` while we use `time.Modtime` which uses `time.Local` as its
location.
Fixes https://github.com/tetratelabs/func-e/issues/303.
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

Parse date string using system local as its timezone

---

internal/moreos/moreos_func-e_test.go
internal/moreos/testdata/fake_func-e.go

This is a follow-up for https://github.com/tetratelabs/func-e/pull/371#pullrequestreview-752322738 to test a set of possible signals (`SIGINT`, `SIGTERM`, `SIGKILL`) to terminate func-e.
A minor change on checking the stderr: this PR uses a scanner instead of peeking on the buffer since for some reason redirecting `cmd.Stderr` to a buffer doesn't give complete stderr after the process is terminated. Hence here we use a scanner to `io.ReadCloser` returned by `cmd.StderrPipe()` instead.
Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

Add tests calling terminating signals to func-e

---

.github/workflows/commit.yaml
.github/workflows/internal-images.yml
RATIONALE.md

A lot of thought went into the decision of whether or not to use
emulation for arm64. However, this was spread out across discussions and
PRs, but not in the codebase. This adds a RATIONALE section with the
background, which is that this is temporary until GHA supports arm64.
Note, the same would apply if we start supporting s390x, except we don't
at the moment, which is why that isn't mentioned. s390x support would
need to happen first in Envoy.
Obviates #373

Pushes internal arm64 CentOS image and adds RATIONALE.md about Travis

---

internal/envoy/run.go
internal/envoy/runtime.go
internal/envoy/shutdown.go
internal/moreos/testdata/fake_func-e.go

This addresses some fuzz to make sure the comments don't lie. Notably,
this defers contexts the same way between fake and real. This also pulls
out handleShutdown to accent notes from #372

Makes fake_func-e more consistent with real func-e

---

.github/workflows/commit.yaml
.github/workflows/internal-images.yml
.github/workflows/msi.yaml
.github/workflows/release.yaml
.travis.yml
Makefile

This removes the hard requirement to build with exactly the same version
of go as indicated in the go.mod file. This allows more flexibility when
new versions of go (such as 1.18) are released.
This also removes the requirement to track down to the patch of go.
Instead, this builds with the latest patch of go that's available at the
time.
Go versions aren't often released, but this removes maintenance each
time that happens. It also allows us to more easily cache golang
installs in our Docker image, and without tight coupling to what GitHub
actions uses.

Removes go version maintenance

---

.github/workflows/internal-images.yml

There's value in having all GitHub workflows being consistent in how
they declare the minor version of go we want. There's a strange nuance,
which is that GHA matrix variables cannot interpolate env variables.
Instead, this supplies the same value using a Docker build arg. Now, all
workflows that rely on go have a similar env header, which makes it
easier to update consistently, despite the inconsistency in how GHA
interpolates variables!

Uses Docker build arg to set go version

---

.github/workflows/internal-images.yml

This matches the minor revision of go with the current GitHub Actions
runner instead of looking up latest using gimme. Doing so removes
complexity around what gimme is, and why figuring out the latest go
revision for a minor isn't straight-forward [1].
[1] Unlike a lot of projects, go does not attach binaries to releases.
This makes a potential race between a tag being pushed and binaries
being available. Moreover, there are release tags for release
canditates, so filtering these out requires logic. The way to get the
best known latest revision is to parse https://golang.org/dl, as that
is the most official source of what is the latest minor. However,
parsing that is tricky, so if we did, we might as well re-use gimme.
Ex.
```yaml
run: | …
```

Matches minor revision of go of CentOS image with GHA runner

---

.github/workflows/commit.yaml
.github/workflows/configure_go.sh
.github/workflows/internal-images.yml
.github/workflows/msi.yaml
.github/workflows/release.yaml

This avoids any version differences between running e2e tests via Docker
(ex for CentOS) vs a normal run (Ubuntu, MacOS, etc). It accomplishes
this by using the built-in GOROOT variable.
go.mod controls which GOROOT is used, and in doing so, this removes
maintenance.
This includes a temporary workaround because MacOS does not have the
same variable as Windows and Ubuntu. Once the below is solved, we can
simply delete the workaround.
https://github.com/actions/virtual-environments/issues/4156

Ensures Ubuntu runs the same version of go as CentOS

---

.github/workflows/commit.yaml
.github/workflows/configure_go.sh
.github/workflows/msi.yaml
.github/workflows/release.yaml
.licenserignore
.travis.yml
Makefile
Tools.mk

This switches from external (GitHub Actions workflow) to internal
(Makefile) for configuring GOROOT. Doing so reduces the amount of
copy/paste.
This also drops build cache, and moves tools to `Tools.mk` to
make the go cache config simpler and more precise.
A future change will remove configure_go.sh entirely, by rewriting how
internal images are produced.

Detects GOROOT for go.mod using make

---

Makefile
e2e/func-e_versions_test.go

While testing on Windows 11, I noticed I had an old default version of envoy in my ~/.func-e/version file. This took too long to understand, so I changed the tests to not assume `func-e versions` will have the latest version downloaded.

Makes e2e tests less sensitive to user env

---

Makefile
e2e/func-e_use_test.go
e2e/func-e_versions_test.go
internal/cmd/help_test.go
internal/cmd/run.go
internal/cmd/run_cmd_test.go
internal/cmd/run_test.go
internal/cmd/use.go
internal/cmd/versions.go
internal/envoy/runtime.go
internal/envoy/version.go
internal/envoy/version_test.go
internal/envoy/versions.go
internal/envoy/versions_test.go

This removes an api for acknowledgement of the initial state. Doing so
also reduces file IO when environment variables select the version, as
in this case no default version file will be created.
This also fixes a bug where we had a false-positive on version selection.
Versions are platform-specific so we need to only be ok when the
current platform's tarball is available.
Next, this alerts the user when a remote lookup is happening. This was
missed before as we didn't let users know we are remotely resolving the
latest version.
Finally, this ensures there's enough information in warnings and errors
to troubleshoot a missing release. Particularly, there are cases where a
version is available, but not across the board. For example, linux exists,
but darwin does not.

Cleans up version selection logic

---

Makefile
internal/version/version.go
internal/version/version_test.go
lint/last_known_envoy_test.go

This changes the logic that verfies last_known_envoy.txt such that it
only expects updates when all supported platforms are available.
Before, this would update when the first platform was available, which
would break development (ex linux out before macOS).
Note: this doesn't address the similar problem at runtime, and a variant
of the problem in the e2e tests. This PR is standalone to highlight the
switch from using `jq` to go for linting.
See #393

Ensures last_known_envoy.txt doesn't reference an inconsistent version

---

internal/cmd/run.go
internal/cmd/run_test.go
internal/envoy/versions_test.go
internal/test/server.go
internal/version/version.go
internal/version/version_test.go
lint/last_known_envoy_test.go

This stops reading latestRelease in the envoy-versions.json as it is not
platform-specific and causes usability and test glitches. Instead, the
last available version is looked up based on the current platform.
Notably, this allows linux to release ahead of macOS and without causing
problems.
Fixes #393

Ignores latestRelease in envoy-versions.json

---

Makefile

Previously, we used an invalid pattern style as regex isn't supported.
It was interpreted as a character class and resulted in invalid
filtering. Specifically, this prevented the "moreos" package from
showing up in coverage results. To fix this portably, we enumerate known
depths of what we don't want. Doing this looks explicit, but it
shouldn't result in high maintenance as this project isn't likely to
have deep package hierarchies.
Note: moreos is in the output and we also include globals even though it has no tests (only constants)
```bash
$ make clean test
clean      deleting temporary files
clean      ok
test       running unit tests
ok  	github.com/tetratelabs/func-e	1.065s
ok  	github.com/tetratelabs/func-e/internal/cmd	9.297s
ok  	github.com/tetratelabs/func-e/internal/envoy …
```

Fixes patterns used to weed out test sources

---

e2e/func-e_run_test.go
internal/cmd/app_test.go
internal/cmd/run_cmd_test.go
internal/cmd/use_test.go
internal/cmd/versions_cmd_test.go
internal/cmd/which_test.go
internal/envoy/install_test.go

Reference: https://golang.org/doc/go1.14#testing
Since the `t *testing.T` is being passed through many functions, we should use t.Cleanup(func() { }) to clean stuff instead of letting each individual test cases do this.

Use t.Cleanup function to clean stuff after tests

---

.github/workflows/commit.yaml
.github/workflows/packaging.yaml
.github/workflows/release.yaml

func-e is an introductory tool, so we can optimize to test the latest
available OS vs what GitHub Actions marks as latest (often years old).
Note: MacOS 12 is not supported on GHA, still!
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

Uses latest runners when running tests

---

site/content/_index.md

Currently it includes the leading $, and includes the whole block, this
change removes the leading $ and splits it into two blocks, one for the
install command, and the other to run func-e

Make the example on func-e.io pastable into a terminal

---

USAGE.md
internal/cmd/app.go
internal/cmd/testdata/func-e_help.txt
packaging/nfpm/func-e.8

FUNC_E_PLATFORM likely only works when changing CPU architecture. This adds notes about that.
Closes #439

Clarifies use of FUNC_E_PLATFORM

---

api/run.go
api/run_test.go

* Define an api that allows go projects to use func-e as a library
Takes https://github.com/tetratelabs/func-e/pull/434 forward
Fixes: https://github.com/tetratelabs/func-e/issues/433

Allow downstream projects to import func-e

---

api/run.go
api/run_test.go
internal/envoy/run.go
internal/globals/globals.go

Reverts tetratelabs/func-e#456
This was a wrong way and was a workaround of a bug in the implementation detail here that shouldn't be a part of API

Revert "ExitChannel to allow to wait for envoy process to exit"

---

api/run.go
api/run_test.go
internal/cmd/run_cmd_test.go
internal/envoy/run.go
internal/envoy/run_test.go
internal/envoy/runtime.go
internal/envoy/shutdown.go
internal/envoy/shutdown/admin.go
internal/envoy/shutdown/admin_test.go
internal/test/envoy.go
main.go

Redo of #456. Basically, the original impl had a race condition and cannot wait for the Envoy processes to actually exit plus there was a race condition when accessing exec.Process objects. This fixes it altogether by decoupling internal/envoy/run implementation from the actual signal handling and making it focus on the simple context cancelation.

fixes race condition in Run by decoupling singal handling from the impl

---

internal/envoy/run.go
internal/envoy/run_test.go
internal/moreos/moreos_func-e_test.go

func-e runs Envoy for given args, so there's no reason to log all arguments as that should be trivial to users. The only portion that is not trivial during debugging is the binary location managed by func-e, so this switches to print it only. This will suppress crazy large output by a library user such as Envoy Gateway that passes a giant literal yaml.

Suppress noisy logging

---

api/run.go

`globals.DefaultHomeDir` is used in text description, "" is the value to use for default

Fix run default which made a directory literally named ${HOME}
