- .golangci.yml
- ci/format
- ci/install
- ci/lint
- cmd/getenvoy/main.go
- pkg/cmd/root.go
- pkg/manifest/fetch.go
- pkg/manifest/fetch_test.go
- pkg/manifest/print_test.go
> Turn on golangci-lint

- .golangci.yml
- pkg/binary/run.go
- pkg/cmd/root.go
- pkg/cmd/run.go
The UX is pretty awful/has no value add right now. This is part of an iterative process towards a bare-bones `getenvoy list/pull/run`.
> Add initial run for local files

- CONTRIBUTING.md
> fix up contributing

- README.md
> Update readme to point at repo page

- go.mod
- go.sum
- pkg/manifest/fetch_test.go
- pkg/manifest/testdata/list.golden
- pkg/manifest/testdata/manifest.golden
> Update to most recent manifest changes

- pkg/manifest/locate.go
- pkg/manifest/locate_test.go
- pkg/manifest/print_test.go
- pkg/manifest/testdata/manifest.golden
> Add binary locater to manifest API

- pkg/manifest/locate.go
- pkg/manifest/locate_test.go
- pkg/manifest/platform_darwin.go
- pkg/manifest/platform_linux.go
> Autofill Platform if not passed in via reference

- .circleci/config.yml
- .gitignore
- .goreleaser.yaml
I have no way of verifying if this works other than trying it... ¯\_(ツ)_/¯
> autobuild release on new tag

- pkg/binary/envoy/debug/admin_test.go
- pkg/binary/envoy/debug/log_linux_test.go
- pkg/binary/envoy/debug/node_test.go
- pkg/binary/envoy/run.go
> Tar and clean up debug data post-termination of Envoy

- .circleci/config.yml
- .gitignore
- .goreleaser.yaml
- Dockerfile
- Makefile
> Add Docker images to releaser

- .goreleaser.yaml
> add latest docker image to releaser

- go.sum
- pkg/cmd/doc.go
- pkg/cmd/fetch.go
- pkg/cmd/list.go
- pkg/cmd/root.go
- pkg/cmd/run.go
> Tidy up cli docs for public release

- .goreleaser.yaml
> Make goreleaser changelog less conservative

- pkg/cmd/root.go
> Remove autogen tag from doc generation

- pkg/cmd/doc.go
> support parent/command fields in docs command

- go.mod
- go.sum
- pkg/binary/envoy/controlplane/istio.tmpl.go
- pkg/binary/envoy/controlplane/istio.tmpl_test.go
> Pin bootstrap to an Istio version

- pkg/binary/envoy/config.go
- pkg/binary/envoy/controlplane/istio.go
- pkg/binary/envoy/controlplane/istio_test.go
- pkg/cmd/run.go
> change router mode into loadbalancer mode

- pkg/cmd/run.go
> move experimental warning to front of flags

- pkg/binary/envoy/fetch.go
- pkg/binary/envoy/fetch_test.go
Signed-off-by: Lizan Zhou <lizan@tetrate.io>
> support any compressions supported by the library including xz

- .goreleaser.yaml
- pkg/cmd/root.go
- fixes #56 
Task to accomplish
- sample output
```sh
$ ./dist/getenvoy_linux_amd64/getenvoy --version
getenvoy version 0.2.5
```
Signed-off-by: Hengyuan <jhy8890948@gmail.com>
> Version Flag

- .circleci/config.yml
- .goreleaser.yaml
- Makefile
- ci/install-lint
> Update docker release versions

- pkg/manifest/locate.go
This issue exposes functions relevant for the manifest validation test scripts
- related to https://github.com/tetrateio/tetrate/issues/2188
igned-off-by: Hengyuan <jhy8890948@gmail.com>
> expose functions for manifest validation

- .github/workflows/release.yaml
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
Fix to #121
> Fix release tag script.

- go.mod
- go.sum
- pkg/cmd/extension/common/toolchain.go
- pkg/cmd/extension/push/cmd.go
- pkg/cmd/extension/push/cmd_test.go
- pkg/extension/wasmimage/puller.go
- pkg/extension/wasmimage/pusher.go
- pkg/extension/wasmimage/wasmimage.go
- pkg/extension/wasmimage/wasmimage_test.go
- pkg/extension/workspace/config/toolchain/builtin/helpers.go
- test/e2e/getenvoy_extension_push_test.go
> Removes dependency on docker distribution

- .github/workflows/release.yaml
- .gitignore
- Makefile
- test/e2e/main_test.go
> Deduplicates make config and removes orphaned config

- pkg/cmd/doc_test.go
- pkg/cmd/fetch.go
- pkg/cmd/help_test.go
- pkg/cmd/testdata/getenvoy_fetch.md
- pkg/cmd/testdata/getenvoy_fetch_help.txt
- pkg/cmd/testdata/getenvoy_help.txt
- pkg/cmd/testdata/getenvoy_list_help.txt
- pkg/cmd/testdata/getenvoy_run_help.txt
> Adds help test to ensure we know what changes

- .goreleaser.yaml
- internal/cmd/app.go
- internal/cmd/testdata/getenvoy.md
- internal/cmd/testdata/getenvoy_help.txt
Changes from defaults should be commented or removed
> Disables auto-changelog and uses more defaults in goreleaser

- site/envoy-versions.json
To help next person. We intentionally only added non-EOL versions, but seems we need to give folks time to get there cc @nheaps-chwy
See #261
> Adds EOL versions to help folks migrate

- .github/workflows/commit.yaml
- .github/workflows/release.yaml
- .github/workflows/site.yaml
- .travis.yml
security patches and little fixes around go.mod
> Updates to go 1.16.5

- site/envoy-versions.json
> Adds 1.16.3 to help work around upgrade issues

- README.md
- e2e/getenvoy_run_test.go
This dodges a windows compatability problem and upcoming v1.19 one as
well. This also tidies the README.
Fixes #273
> Switches to simpler and more OS-portable one-liner

- site/README.md
- site/envoy-versions_test.go
This unblocks us from making the CI test windows and arm64 compatibility
> Adds temporary repository instructions

- .github/workflows/commit.yaml
while opaque, make is actually in there!
> Uses make from GHA runner on Windows

- .gitattributes
- .github/workflows/commit.yaml
This simplifies test runner configuration
> Handles lf in .gitattributes

- packaging/msi/winget_manifest.sh
thanks for the idea @mathetake!
> moves to lowest common shasum

- README.md
> Adds vanity downloads

- .github/workflows/commit.yaml
- .travis.yml
- Next.mk
This also runs them on commit as we are getting closer to a cutover.
PS I think the make help isn't quite right, so if someone wants to push a commit to fix that please do!
```bash
$ make -f Next.mk help
func-e
help       Describe how to use each target
build      Build the func-e binary
test       Run all unit tests
```
See #352
> Converts e2e to new Makefile

- Makefile
Before, our test coverage was accidentally 0.5% higher than it should be
due to inclusion of packages not in the binary (notably test utilities).
This fixes it in native make, which helps us maintain what is main or
not in one place. We use make-derived source lists in order to taint
targets properly.
> Fixes unnaturally high test coverage by excluding test utilities

- .github/workflows/commit.yaml
per https://github.com/tetratelabs/func-e/pull/430#pullrequestreview-988563702
> Removes secret from codecov upload

- .github/workflows/release.yaml
Signed-off-by: Edoardo Vacchi <evacchi@users.noreply.github.com>
> build: fix Windows build when secrets are missing

- internal/envoy/http.go
- internal/envoy/http_test.go
- internal/envoy/install.go
- internal/envoy/runtime.go
- internal/envoy/startup.go
- internal/envoy/startup_test.go
- internal/envoy/versions.go
this is in preparation of being able to use synctest where you really need to be able to control the client
> Refactor http client properly
